Repository WayToEarth-Team/WayToEarth_BE, pull requests merged in 2025-09, with the labels that each got.

#54 [FEAT] Feed 좋아요 토글 시 likeCount 불일치 문제 수정
  src/main/java/com/waytoearth/repository/Feed/FeedRepository.java
  src/main/java/com/waytoearth/service/feed/FeedService.java
Labels: gang

#58 [FEAT] 카카오 중계서버 방식 제거 및 SDK 로그인 방식 변경
  src/main/java/com/waytoearth/controller/v1/Auth/AuthController.java
  src/main/java/com/waytoearth/dto/request/auth/KakaoLoginRequest.java
  src/main/java/com/waytoearth/dto/response/feed/FeedResponse.java
  src/main/java/com/waytoearth/entity/Feed/Feed.java
  src/main/java/com/waytoearth/entity/emblem/UserEmblem.java
  src/main/java/com/waytoearth/repository/Feed/FeedRepositoryImpl.java
  src/main/java/com/waytoearth/service/auth/AuthService.java
  src/main/java/com/waytoearth/service/auth/KakaoApiService.java
  src/main/java/com/waytoearth/service/running/RunningServiceImpl.java
Labels: gang, fix

#62 feat : Journey Running 시스템 1차 구현 및 스웨거 명세 추가
  FINAL_REVIEW_REPORT.md
  JOURNEY_RUNNING_CONVERSION.md
  Journey_Running_API_Postman_Collection.json
  Journey_Running_Environment.postman_environment.json
  MIGRATION_PLAN.md
  POSTMAN_TEST_GUIDE.md
  src/main/java/com/waytoearth/config/Swagger/SwaggerConfig.java
  src/main/java/com/waytoearth/controller/v1/Journey/GuestbookController.java
  src/main/java/com/waytoearth/controller/v1/Journey/JourneyController.java
  src/main/java/com/waytoearth/controller/v1/Journey/JourneyProgressController.java
  src/main/java/com/waytoearth/controller/v1/Journey/LandmarkController.java
  src/main/java/com/waytoearth/controller/v1/Journey/StampController.java
  src/main/java/com/waytoearth/controller/v1/Journey/StoryCardController.java
  src/main/java/com/waytoearth/dto/Journey/request/GuestbookCreateRequest.java
  src/main/java/com/waytoearth/dto/Journey/request/JourneyProgressUpdateRequest.java
  src/main/java/com/waytoearth/dto/Journey/request/JourneyStartRequest.java
  src/main/java/com/waytoearth/dto/Journey/request/StampCollectRequest.java
  src/main/java/com/waytoearth/dto/Journey/response/GuestbookResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/JourneyCompletionEstimateResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/JourneyProgressResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/JourneySummaryResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/LandmarkDetailResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/LandmarkSummaryResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/StampResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/StoryCardResponse.java
  src/main/java/com/waytoearth/dto/Journey/response/UserSummaryResponse.java
  src/main/java/com/waytoearth/dto/request/running/RunningStartRequest.java
  src/main/java/com/waytoearth/entity/Journey/GuestbookEntity.java
  src/main/java/com/waytoearth/entity/Journey/GuestbookLikeEntity.java
  src/main/java/com/waytoearth/entity/Journey/GuestbookReportEntity.java
  src/main/java/com/waytoearth/entity/Journey/JourneyEntity.java
  src/main/java/com/waytoearth/entity/Journey/LandmarkEntity.java
  src/main/java/com/waytoearth/entity/Journey/StampEntity.java
  src/main/java/com/waytoearth/entity/Journey/StoryCardEntity.java
  src/main/java/com/waytoearth/entity/Journey/UserJourneyProgressEntity.java
  src/main/java/com/waytoearth/entity/enums/RunningType.java
  src/main/java/com/waytoearth/repository/Journey/GuestbookRepository.java
  src/main/java/com/waytoearth/repository/Journey/JourneyRepository.java
  src/main/java/com/waytoearth/repository/Journey/LandmarkRepository.java
  src/main/java/com/waytoearth/repository/Journey/StampRepository.java
  src/main/java/com/waytoearth/repository/Journey/StoryCardRepository.java
  src/main/java/com/waytoearth/repository/Journey/UserJourneyProgressRepository.java
  src/main/java/com/waytoearth/service/Journey/GuestbookService.java
  src/main/java/com/waytoearth/service/Journey/GuestbookServiceImpl.java
  src/main/java/com/waytoearth/service/Journey/JourneyService.java
  src/main/java/com/waytoearth/service/Journey/JourneyServiceImpl.java
  src/main/java/com/waytoearth/service/Journey/LandmarkService.java
  src/main/java/com/waytoearth/service/Journey/LandmarkServiceImpl.java
  src/main/java/com/waytoearth/service/Journey/StampService.java
  src/main/java/com/waytoearth/service/Journey/StampServiceImpl.java
Labels: gang

#66 feat : 방명록 photo url 필드 및 메서드 제거
  src/main/java/com/waytoearth/controller/v1/journey/GuestbookController.java
  src/main/java/com/waytoearth/dto/request/journey/GuestbookCreateRequest.java
  src/main/java/com/waytoearth/dto/response/journey/GuestbookResponse.java
  src/main/java/com/waytoearth/entity/journey/GuestbookEntity.java
  src/main/java/com/waytoearth/service/journey/GuestbookServiceImpl.java
Labels: gang, fix

#68 Journey route entity 추가, 경로 제공 api 구현 및 방명록 좋아요 엔티티 제거
  FINAL_REVIEW_REPORT.md
  JOURNEY_ROUTE_PR_DESCRIPTION.md
  src/main/java/com/waytoearth/controller/v1/journey/JourneyRouteController.java
  src/main/java/com/waytoearth/dto/response/journey/JourneyRouteResponse.java
  src/main/java/com/waytoearth/entity/journey/GuestbookLikeEntity.java
  src/main/java/com/waytoearth/entity/journey/JourneyEntity.java
  src/main/java/com/waytoearth/entity/journey/JourneyRouteEntity.java
  src/main/java/com/waytoearth/repository/journey/JourneyRouteRepository.java
  src/main/java/com/waytoearth/service/journey/JourneyService.java
  src/main/java/com/waytoearth/service/journey/JourneyServiceImpl.java
Labels: gang, feature, fix

#73 Feat/crew system with ranking - 동시성 문제 해결 및 성능 최적화
  chat_test.html
  crew-system-improvements.md
  src/main/java/com/waytoearth/config/scheduling/ChatSchedulerConfig.java
  src/main/java/com/waytoearth/config/security/SecurityConfig.java
  src/main/java/com/waytoearth/config/websocket/WebSocketConfig.java
  src/main/java/com/waytoearth/controller/v1/crew/CrewChatController.java
  src/main/java/com/waytoearth/controller/v1/crew/CrewController.java
  src/main/java/com/waytoearth/controller/v1/crew/CrewJoinController.java
  src/main/java/com/waytoearth/controller/v1/crew/CrewMemberController.java
  src/main/java/com/waytoearth/controller/v1/crew/CrewStatisticsController.java
  src/main/java/com/waytoearth/controller/v1/file/FileController.java
  src/main/java/com/waytoearth/dto/request/crew/ChatMessageRequest.java
  src/main/java/com/waytoearth/dto/request/crew/CrewCreateRequest.java
  src/main/java/com/waytoearth/dto/request/crew/CrewJoinRequest.java
  src/main/java/com/waytoearth/dto/request/crew/CrewUpdateRequest.java
  src/main/java/com/waytoearth/dto/request/crew/JoinRequestProcessRequest.java
  src/main/java/com/waytoearth/dto/request/crew/MemberRoleChangeRequest.java
  src/main/java/com/waytoearth/dto/request/crew/OwnershipTransferRequest.java
  src/main/java/com/waytoearth/dto/response/crew/CrewChatMessageDto.java
  src/main/java/com/waytoearth/dto/response/crew/CrewDetailResponse.java
  src/main/java/com/waytoearth/dto/response/crew/CrewListResponse.java
  src/main/java/com/waytoearth/dto/response/crew/CrewMemberResponse.java
  src/main/java/com/waytoearth/dto/response/crew/JoinRequestResponse.java
  src/main/java/com/waytoearth/dto/websocket/ChatMessage.java
  src/main/java/com/waytoearth/entity/crew/CrewChatEntity.java
  src/main/java/com/waytoearth/entity/crew/CrewChatNotificationSettingEntity.java
  src/main/java/com/waytoearth/entity/crew/CrewChatReadStatusEntity.java
  src/main/java/com/waytoearth/entity/crew/CrewEntity.java
  src/main/java/com/waytoearth/entity/crew/CrewMemberEntity.java
  src/main/java/com/waytoearth/entity/crew/CrewStatisticsEntity.java
  src/main/java/com/waytoearth/exception/CrewNotFoundException.java
  src/main/java/com/waytoearth/exception/UnauthorizedAccessException.java
  src/main/java/com/waytoearth/repository/crew/CrewChatNotificationSettingRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewChatReadStatusRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewChatRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewJoinRequestRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewMemberRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewRepository.java
  src/main/java/com/waytoearth/repository/crew/CrewStatisticsRepository.java
  src/main/java/com/waytoearth/service/crew/CrewChatService.java
  src/main/java/com/waytoearth/service/crew/CrewChatServiceImpl.java
  src/main/java/com/waytoearth/service/crew/CrewJoinServiceImpl.java
  src/main/java/com/waytoearth/service/crew/CrewMemberServiceImpl.java
  src/main/java/com/waytoearth/service/crew/CrewService.java
  src/main/java/com/waytoearth/service/crew/CrewServiceImpl.java
  src/main/java/com/waytoearth/service/crew/CrewStatisticsService.java
  src/main/java/com/waytoearth/service/crew/CrewStatisticsServiceImpl.java
  src/main/java/com/waytoearth/service/file/FileService.java
  src/main/java/com/waytoearth/util/ChatRateLimiter.java
  src/main/java/com/waytoearth/util/MessageSanitizer.java
  src/main/java/com/waytoearth/websocket/CrewChatWebSocketHandler.java
  src/main/java/com/waytoearth/websocket/WebSocketAuthInterceptor.java
Labels: gang, refactor

#74 feat : 웹소켓 배포용 origin 설정
  src/main/java/com/waytoearth/config/scheduling/ChatSchedulerConfig.java
  src/main/java/com/waytoearth/config/websocket/WebSocketConfig.java
Labels: gang, fix

#78 fix: 보안 취약점 수정 - 민감한 정보 로깅 문제 해결
  src/main/java/com/waytoearth/WaytoearthBackendApplication.java
  src/main/java/com/waytoearth/service/auth/JwtTokenProvider.java
  src/main/java/com/waytoearth/util/ChatRateLimiter.java
Labels: smin, fix

#79 feat: Redis ZSet 기반 실시간 크루 랭킹 시스템 구현
  .claude/settings.local.json
  .gitignore
  build.gradle
  src/main/java/com/waytoearth/config/redis/RedisConfig.java
  src/main/java/com/waytoearth/service/crew/CrewStatisticsServiceImpl.java
  src/main/java/com/waytoearth/service/ranking/CrewRankingService.java
  src/main/java/com/waytoearth/service/ranking/CrewRankingServiceImpl.java
  src/main/java/com/waytoearth/util/RankingKeyUtil.java
  src/main/resources/application.yml
Labels: smin, feature
